@echo off
echo Finalizando SystemSettings.exe...
taskkill -F -FI "IMAGENAME eq SystemSettings.exe"

echo Parando serviços do Windows Update...
net stop wuauserv
net stop UsoSvc

echo Atualizando políticas de grupo...
gpupdate /force

echo Limpando pasta SoftwareDistribution...
rd /s /q "C:\Windows\SoftwareDistribution"
md "C:\Windows\SoftwareDistribution"

echo Iniciando serviços do Windows Update...
net start wuauserv
net start UsoSvc

echo Finalizando Cortana (SearchUI.exe)...
taskkill /F /IM SearchUI.exe

echo Desabilitando Cortana...
move "%windir%\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy" "%windir%\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy.bak"

echo Limpando downloads do Windows Update...
del /s /f /q %WinDir%\SoftwareDistribution\Download\*.*

echo Removendo arquivos de upgrade do Windows 10...
takeown /F %SYSTEMDRIVE%\Windows10Upgrade\* /R /A /D Y
rmdir /S /Q %SYSTEMDRIVE%\Windows10Upgrade\

echo Removendo arquivos de instalação do Windows 10...
takeown /F "%SYSTEMDRIVE%\Windows 10 install\*" /R /A /D Y
echo Y| cacls "%SYSTEMDRIVE%\Windows 10 install\*.*" /T /grant administrators:F
echo Please wait, this may take a while.
rmdir /S /Q "%SYSTEMDRIVE%\Windows 10 install\"

echo Removendo Windows Defender Health UI...
set WS=%SystemRoot%\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy
takeown /f %WS% /r /a > nul
icacls %WS% /reset /t > nul
rmdir /s /q %WS%

echo Preparando desinstalação do OneDrive...
set x86="%SYSTEMROOT%\System32\OneDriveSetup.exe"
set x64="%SYSTEMROOT%\SysWOW64\OneDriveSetup.exe"
taskkill /f /im OneDrive.exe > NUL 2>&1
ping 127.0.0.1 -n 5 > NUL 2>&1

echo Desinstalando OneDrive...
if exist %x64% (
  %x64% /uninstall
) else (
  %x86% /uninstall
)
ping 127.0.0.1 -n 8 > NUL 2>&1

echo Removendo pastas do OneDrive...
rd "%USERPROFILE%\OneDrive" /Q /S > NUL 2>&1
rd "C:\OneDriveTemp" /Q /S > NUL 2>&1
rd "%LOCALAPPDATA%\Microsoft\OneDrive" /Q /S > NUL 2>&1
rd "%PROGRAMDATA%\Microsoft OneDrive" /Q /S > NUL 2>&1

echo Limpando Windows Search e logs de diagnóstico...
DEL "C:\ProgramData\Microsoft\Search\Data\Applications\Windows\Windows.edb" /s
DEL "C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl" /s
ATTRIB -r "C:\ProgramData\Microsoft\Search\Data\Applications\Windows\Windows.edb"
ATTRIB +r "C:\ProgramData\Microsoft\Search\Data\Applications\Windows\Windows.edb"
ATTRIB -r "C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl"
ATTRIB +r "C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl"

echo Removendo chave de registro do Explorer...
REG Delete "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{12D4C69E-24AD-4923-BE19-31321C43A767}" /f

echo Removendo modo demonstração (RetailDemo)...
takeown /f %ProgramData%\Microsoft\Windows\RetailDemo /r /d y
icacls %ProgramData%\Microsoft\Windows\RetailDemo /grant Administrators:F /T
rd /s /q %ProgramData%\Microsoft\Windows\RetailDemo
takeown /f "C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy\RetailDemo" /r /d y
icacls "C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy\RetailDemo" /grant Administrators:F /T
rd /s /q "C:\Windows\SystemApps\Microsoft.Windows.CloudExperienceHost_cw5n1h2txyewy\RetailDemo"

echo Desabilitando sincronização do OneDrive via registro...
REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows\OneDrive" /v DisableFileSyncNGSC /t REG_DWORD /d 1 /f

echo Finalizando e desinstalando OneDrive (novamente)...
TASKKILL /f /im OneDrive.exe
%SystemRoot%\System32\OneDriveSetup.exe /uninstall
%SystemRoot%\SysWOW64\OneDriveSetup.exe /uninstall
rd "%UserProfile%\OneDrive" /Q /S
rd "%LocalAppData%\Microsoft\OneDrive" /Q /S
rd "%ProgramData%\Microsoft OneDrive" /Q /S
rd "C:\OneDriveTemp" /Q /S

echo Desabilitando SMB1...
dism /online /norestart /disable-feature /featurename:SMB1Protocol

echo Parando e desabilitando serviço de compartilhamento de arquivos...
wmic service where "Name LIKE '%%lanmanserver%%'" call StopService
wmic service where "Name LIKE '%%lanmanserver%%'" call ChangeStartMode Disabled

echo Reiniciando o Explorer...
taskkill /f /im explorer.exe
timeout 2 /nobreak>nul

echo Limpando caches e arquivos temporários do sistema...
DEL /F /S /Q /A %LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db
DEL /f /s /q %systemdrive%\*.tmp
DEL /f /s /q %systemdrive%\*._mp
DEL /f /s /q %systemdrive%\*.log
DEL /f /s /q %systemdrive%\*.gid
DEL /f /s /q %systemdrive%\*.chk
DEL /f /s /q %systemdrive%\*.old
DEL /f /s /q %systemdrive%\recycled\*.*
DEL /f /s /q %systemdrive%\$Recycle.Bin\*.*
DEL /f /s /q %windir%\*.bak
DEL /f /s /q %windir%\prefetch\*.*
rd /s /q %windir%\temp & md %windir%\temp

echo Limpando cookies e arquivos temporários do usuário...
DEL /f /q %userprofile%\cookies\*.*
DEL /f /q %userprofile%\recent\*.*
DEL /f /s /q "%userprofile%\Local Settings\Temporary Internet Files\*.*"
DEL /f /s /q "%userprofile%\Local Settings\Temp\*.*"
DEL /f /s /q "%userprofile%\recent\*.*"
timeout 2 /nobreak>nul

echo Iniciando o Explorer novamente...
start explorer.exe

echo Limpando chaves de inicialização automática no registro...
REG DELETE HKSU\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce /f
REG DELETE HKSU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /f
REG DELETE HKSU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies /f
REG DELETE HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\RunOnce /f
REG DELETE HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Run /f
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServicesOnce /f
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunServices /f
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnceEx /f
REG DELETE HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /f

echo Limpando pastas de inicialização automática...
PUSHD "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
2>Nul RD /S/Q "%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
POPD
PUSHD "%SystemDrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup"
2>Nul RD /S/Q "%SystemDrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup"

echo Parando serviço DiagTrack...
NET STOP DiagTrack

echo Parando serviço diagnosticshub.standardcollector.service...
NET STOP diagnosticshub.standardcollector.service

echo Parando serviço dmwappushservice...
NET STOP dmwappushservice

echo Parando serviço DPS...
NET STOP DPS

echo Parando serviço RemoteRegistry...
NET STOP RemoteRegistry

echo Parando serviço TrkWks...
NET STOP TrkWks

echo Parando serviço WMPNetworkSvc...
NET STOP WMPNetworkSvc

echo Parando serviço WSearch...
NET STOP WSearch

echo Parando serviço SysMain...
NET STOP SysMain

echo Parando serviço dosvc...
net stop dosvc

echo Parando serviço bits...
net stop bits

echo Parando serviço wuauserv...
net stop wuauserv

echo Parando serviço Themes...
net stop Themes

echo Parando serviço InstallService...
net stop InstallService

echo Parando serviço tzautoupdate...
net stop tzautoupdate

echo Parando serviço DisplayEnhancementService...
net stop DisplayEnhancementService

echo Parando serviço SensrSvc...
net stop SensrSvc

echo Parando serviço SensorService...
net stop SensorService

echo Parando serviço WFDSConMgrSvc...
net stop WFDSConMgrSvc

echo Parando serviço TokenBroker...
net stop TokenBroker

echo Parando serviço QWAVE...
net stop QWAVE

echo Parando serviço GraphicsPerfSvc...
net stop GraphicsPerfSvc

echo Parando serviço W32Time...
net stop W32Time

echo Parando serviço SharedAccess...
net stop SharedAccess

echo Parando serviço FDResPub...
net stop FDResPub

echo Parando serviço fdPHost...
net stop fdPHost

echo Parando serviço hidserv...
net stop hidserv

echo Parando serviço CDPSvc...
net stop CDPSvc

echo Parando serviço CertPropSvc...
net stop CertPropSvc

echo Parando serviço AppReadiness...
net stop AppReadiness

echo Parando serviço ALG...
net stop ALG

echo Parando serviço SstpSvc...
net stop SstpSvc

echo Parando serviço ShellHWDetection...
net stop ShellHWDetection

echo Parando serviço SensorDataService...
net stop SensorDataService

echo Parando serviço LanmanServer...
net stop LanmanServer

echo Parando serviço DoSvc...
net stop DoSvc

echo Parando serviço DusmSvc...
net stop DusmSvc

echo Parando serviço EFS...
net stop EFS

echo Parando serviço XboxGipSvc...
net stop XboxGipSvc

echo Parando serviço DevQueryBroker...
net stop DevQueryBroker

echo Desabilitando serviço BDESVC...
sc config "BDESVC" start=disabled

echo Desabilitando serviço EFS...
sc config "EFS" start=disabled

echo Desabilitando serviço DPS...
sc config "DPS" start=disabled

echo Desabilitando serviço WdiServiceHost...
sc config "WdiServiceHost" start=disabled

echo Desabilitando serviço WdiSystemHost...
sc config "WdiSystemHost" start=disabled

echo Desabilitando serviço DiagTrack...
sc config "DiagTrack" start=disabled

echo Desabilitando serviço dmwappushservice...
sc config "dmwappushservice" start=disabled

echo Desabilitando serviço diagnosticshub.standardcollector.service...
sc config "diagnosticshub.standardcollector.service" start=disabled

echo Desabilitando serviço RemoteRegistry...
sc config "RemoteRegistry" start=disabled

echo Desabilitando serviço TrkWks...
sc config "TrkWks" start=disabled

echo Desabilitando serviço WMPNetworkSvc...
sc config "WMPNetworkSvc" start=disabled

echo Desabilitando serviço WSearch...
sc config "WSearch" start=disabled

echo Desabilitando serviço SysMain...
sc config "SysMain" start=disabled

echo Desabilitando serviço CscService...
sc config "CscService" start=disabled

echo Desabilitando serviço MapsBroker...
sc config "MapsBroker" start=disabled

echo Desabilitando serviço CertPropSvc...
sc config "CertPropSvc" start=disabled

echo Configurando serviço wscsvc para iniciar sob demanda...
sc config "wscsvc" start=demand

echo Configurando serviço SystemEventsBroker para iniciar sob demanda...
sc config "SystemEventsBroker" start=demand

echo Configurando serviço tiledatamodelsvc para iniciar sob demanda...
sc config "tiledatamodelsvc" start=demand

echo Configurando serviço WerSvc para iniciar sob demanda...
sc config "WerSvc" start=demand

echo Desabilitando serviço SSDPSRV...
sc config SSDPSRV start=disabled

echo Desabilitando serviço lfsvc...
sc config lfsvc start=disabled

echo Desabilitando serviço AXInstSV...
sc config AXInstSV start=disabled

echo Desabilitando serviço AJRouter...
sc config AJRouter start=disabled

echo Desabilitando serviço AppReadiness...
sc config AppReadiness start=disabled

echo Desabilitando serviço HomeGroupListener...
sc config HomeGroupListener start=disabled

echo Desabilitando serviço HomeGroupProvider...
sc config HomeGroupProvider start=disabled

echo Desabilitando serviço SharedAccess...
sc config SharedAccess start=disabled

echo Desabilitando serviço lltdsvc...
sc config lltdsvc start=disabled

echo Desabilitando serviço wlidsvc...
sc config wlidsvc start=disabled

echo Desabilitando serviço SmsRouter...
sc config SmsRouter start=disabled

echo Desabilitando serviço NcdAutoSetup...
sc config NcdAutoSetup start=disabled

echo Desabilitando serviço PNRPsvc...
sc config PNRPsvc start=disabled

echo Desabilitando serviço p2psvc...
sc config p2psvc start=disabled

echo Desabilitando serviço p2pimsvc...
sc config p2pimsvc start=disabled

echo Desabilitando serviço PNRPAutoReg...
sc config PNRPAutoReg start=disabled

echo Desabilitando serviço WalletService...
sc config WalletService start=disabled

echo Desabilitando serviço icssvc...
sc config icssvc start=disabled

echo Desabilitando serviço XblAuthManager...
sc config XblAuthManager start=disabled

echo Desabilitando serviço XblGameSave...
sc config XblGameSave start=disabled

echo Desabilitando serviço XboxNetApiSvc...
sc config XboxNetApiSvc start=disabled

echo Desabilitando serviço DmEnrollmentSvc...
sc config DmEnrollmentSvc start=disabled

echo Desabilitando serviço RetailDemo...
sc config RetailDemo start=disabled

echo Desabilitando serviço UsoSvc...
sc config "UsoSvc" start=disabled

echo Desabilitando serviço wuauserv...
sc config "wuauserv" start=disabled

echo Parando serviço wsearch...
sc stop wsearch

echo Desabilitando serviço DisplayEnhancementService...
sc config DisplayEnhancementService start=disabled

echo Desabilitando serviço DusmSvc...
sc config DusmSvc start=disabled

echo Desabilitando serviço TabletInputService...
sc config TabletInputService start=disabled

echo Desabilitando serviço Fax...
sc config Fax start=disabled

echo Desabilitando serviço WpcMonSvc...
sc config WpcMonSvc start=disabled

echo Desabilitando serviço SessionEnv...
sc config SessionEnv start=disabled

echo Desabilitando serviço MicrosoftEdgeElevationService...
sc config MicrosoftEdgeElevationService start=disabled

echo Desabilitando serviço edgeupdate...
sc config edgeupdate start=disabled

echo Desabilitando serviço edgeupdatem...
sc config edgeupdatem start=disabled

echo Desabilitando serviço autotimesvc...
sc config autotimesvc start=disabled

echo Desabilitando serviço TermService...
sc config TermService start=disabled

echo Desabilitando serviço SensorDataService...
sc config SensorDataService start=disabled

echo Desabilitando serviço SensorService...
sc config SensorService start=disabled

echo Desabilitando serviço SensrSvc...
sc config SensrSvc start=disabled

echo Desabilitando serviço shpamsvc...
sc config shpamsvc start=disabled

echo Desabilitando serviço PhoneSvc...
sc config PhoneSvc start=disabled

echo Desabilitando serviço TapiSrv...
sc config TapiSrv start=disabled

echo Desabilitando serviço UevAgentService...
sc config UevAgentService start=disabled

echo Desabilitando serviço TokenBroker...
sc config TokenBroker start=disabled

echo Desabilitando serviço WebClient...
sc config WebClient start=disabled

echo Desabilitando serviço MixedRealityOpenXRSvc...
sc config MixedRealityOpenXRSvc start=disabled

echo Desabilitando serviço stisvc...
sc config stisvc start=disabled

echo Desabilitando serviço WbioSrvc...
sc config WbioSrvc start=disabled

echo Desabilitando serviço Wecsvc...
sc config Wecsvc start=disabled

echo Desabilitando serviço XboxGipSvc...
sc config XboxGipSvc start=disabled

echo Desabilitando serviço SEMgrSvc...
sc config SEMgrSvc start=disabled

echo Desabilitando serviço iphlpsvc...
sc config iphlpsvc start=disabled

echo Desabilitando serviço Backupper Service...
sc config "Backupper Service" start=disabled

echo Desabilitando serviço BthAvctpSvc...
sc config BthAvctpSvc start=disabled

echo Desabilitando serviço cbdhsvc...
sc config cbdhsvc start=disabled

echo Desabilitando serviço CDPSvc...
sc config CDPSvc start=disabled

echo Desabilitando serviço CDPUserSvc...
sc config CDPUserSvc start=disabled

echo Desabilitando serviço DevQueryBroker...
sc config DevQueryBroker start=disabled

echo Desabilitando serviço DevicesFlowUserSvc...
sc config DevicesFlowUserSvc start=disabled

echo Desabilitando serviço dmwappushservice...
sc config dmwappushservice start=disabled

echo Desabilitando serviço DispBrokerDesktopSvc...
sc config DispBrokerDesktopSvc start=disabled

echo Desabilitando serviço TrkWks...
sc config TrkWks start=disabled

echo Desabilitando serviço dLauncherLoopback...
sc config dLauncherLoopback start=disabled

echo Desabilitando serviço EFS...
sc config EFS start=disabled

echo Desabilitando serviço fdPHost...
sc config fdPHost start=disabled

echo Desabilitando serviço FDResPub...
sc config FDResPub start=disabled

echo Desabilitando serviço IKEEXT...
sc config IKEEXT start=disabled

echo Desabilitando serviço NPSMSvc...
sc config NPSMSvc start=disabled

echo Desabilitando serviço WPDBusEnum...
sc config WPDBusEnum start=disabled

echo Desabilitando serviço PcaSvc...
sc config PcaSvc start=disabled

echo Desabilitando serviço RasMan...
sc config RasMan start=disabled

echo Desabilitando serviço RetailDemo...
sc config RetailDemo start=disabled

echo Desabilitando serviço SstpSvc...
sc config SstpSvc start=disabled

echo Desabilitando serviço ShellHWDetection...
sc config ShellHWDetection start=disabled

echo Desabilitando serviço SSDPSRV...
sc config SSDPSRV start=disabled

echo Desabilitando serviço SysMain...
sc config SysMain start=disabled

echo Desabilitando serviço OneSyncSvc...
sc config OneSyncSvc start=disabled

echo Desabilitando serviço lmhosts...
sc config lmhosts start=disabled

echo Desabilitando serviço UserDataSvc...
sc config UserDataSvc start=disabled

echo Desabilitando serviço UnistoreSvc...
sc config UnistoreSvc start=disabled

echo Desabilitando serviço Wcmsvc...
sc config Wcmsvc start=disabled

echo Desabilitando serviço FontCache...
sc config FontCache start=disabled

echo Desabilitando serviço W32Time...
sc config W32Time start=disabled

echo Desabilitando serviço tzautoupdate...
sc config tzautoupdate start=disabled

echo Desabilitando serviço DsSvc...
sc config DsSvc start=disabled

echo Desabilitando serviço DevicesFlowUserSvc_5f1ad...
sc config DevicesFlowUserSvc_5f1ad start=disabled

echo Desabilitando serviço diagsvc...
sc config diagsvc start=disabled

echo Desabilitando serviço DialogBlockingService...
sc config DialogBlockingService start=disabled

echo Desabilitando serviço PimIndexMaintenanceSvc_5f1ad...
sc config PimIndexMaintenanceSvc_5f1ad start=disabled

echo Desabilitando serviço MessagingService_5f1ad...
sc config MessagingService_5f1ad start=disabled

echo Desabilitando serviço AppVClient...
sc config AppVClient start=disabled

echo Desabilitando serviço MsKeyboardFilter...
sc config MsKeyboardFilter start=disabled

echo Desabilitando serviço NetTcpPortSharing...
sc config NetTcpPortSharing start=disabled

echo Desabilitando serviço ssh-agent...
sc config ssh-agent start=disabled

echo Desabilitando serviço OneSyncSvc_5f1ad...
sc config OneSyncSvc_5f1ad start=disabled

echo Desabilitando serviço wercplsupport...
sc config wercplsupport start=disabled

echo Desabilitando serviço WMPNetworkSvc...
sc config WMPNetworkSvc start=disabled

echo Desabilitando serviço WerSvc...
sc config WerSvc start=disabled

echo Desabilitando serviço WpnUserService_5f1ad...
sc config WpnUserService_5f1ad start=disabled

echo Desabilitando serviço WinHttpAutoProxySvc...
sc config WinHttpAutoProxySvc start=disabled

echo Desabilitando serviço DsmSvc...
sc config DsmSvc start=disabled

echo Desabilitando serviço DeviceAssociationService...
sc config DeviceAssociationService start=disabled

echo Desabilitando serviço stisvc...
sc config stisvc start=disabled

echo Parando serviço uhssvc...
sc stop uhssvc

echo Parando serviço upfc...
sc stop upfc

echo Parando serviço PushToInstall...
sc stop PushToInstall

echo Parando serviço BITS...
sc stop BITS

echo Parando serviço InstallService...
sc stop InstallService

echo Parando serviço UsoSvc...
sc stop UsoSvc

echo Parando serviço wuauserv...
sc stop wuauserv

echo Parando serviço LanmanServer...
sc stop LanmanServer

echo Parando serviço ClipSVC...
sc stop ClipSVC

echo Desabilitando serviço ClipSVC...
sc config ClipSVC start=disabled

echo Desabilitando serviço BITS...
sc config BITS start=disabled

echo Desabilitando serviço InstallService...
sc config InstallService start=disabled

echo Desabilitando serviço uhssvc...
sc config uhssvc start=disabled

echo Desabilitando serviço UsoSvc...
sc config UsoSvc start=disabled

echo Desabilitando serviço wuauserv...
sc config wuauserv start=disabled

echo Desabilitando serviço LanmanServer...
sc config LanmanServer start=disabled

echo Desabilitando serviço RemoteRegistry...
sc config RemoteRegistry start=disabled

echo Desabilitando serviço RemoteAccess...
sc config RemoteAccess start=disabled

echo Desabilitando serviço WinRM...
sc config WinRM start=disabled

echo Desabilitando serviço RmSvc...
sc config RmSvc start=disabled

echo Desabilitando serviço PrintNotify...
sc config PrintNotify start=disabled

echo Desabilitando serviço Spooler...
sc config Spooler start=disabled

echo Desabilitando serviço BTAGService...
sc config BTAGService start=disabled

echo Desabilitando serviço bthserv...
sc config bthserv start=disabled

echo Desabilitando serviço NlaSvc...
sc config NlaSvc start=disabled

echo Desabilitando serviço LanmanWorkstation...
sc config LanmanWorkstation start=disabled

echo Configurando serviço BFE para iniciar sob demanda...
sc config BFE start=demand

echo Configurando serviço Dnscache para iniciar sob demanda...
sc config Dnscache start=demand

echo Configurando serviço WinHttpAutoProxySvc para iniciar sob demanda...
sc config WinHttpAutoProxySvc start=demand

echo Configurando serviço Dhcp para iniciar automaticamente...
sc config Dhcp start=auto

echo Configurando serviço DPS para iniciar automaticamente...
sc config DPS start=auto

echo Configurando serviço nsi para iniciar automaticamente...
sc config nsi start=auto

echo Configurando serviço Winmgmt para iniciar automaticamente...
sc config Winmgmt start=auto

echo Configurando serviço WlanSvc para iniciar sob demanda...
sc config WlanSvc start=demand

echo Desabilitando serviço dosvc...
sc config dosvc start=disabled

echo Desabilitando serviço bits...
sc config bits start=disabled

echo Desabilitando serviço diagtrack...
sc config diagtrack start=disabled

echo Desabilitando serviço RetailDemo...
sc config RetailDemo start=disabled

echo Parando serviço DiagTrack...
sc stop DiagTrack

echo Parando serviço dmwappushservice...
sc stop dmwappushservice

echo Parando serviço SysMain...
sc stop SysMain

echo Parando serviço NcdAutoSetup...
sc stop NcdAutoSetup

echo Parando serviço WaasMedicSvc...
sc stop WaasMedicSvc

echo Desabilitando serviço XblAuthManager...
sc config XblAuthManager start=disabled

echo Desabilitando serviço XblGameSave...
sc config XblGameSave start=disabled

echo Desabilitando serviço XboxGipSvc...
sc config XboxGipSvc start=disabled

echo Desabilitando serviço XboxNetApiSvc...
sc config XboxNetApiSvc start=disabled

echo Configurando TCP para usar congestionprovider CTCP...
netsh int tcp set global congestionprovider=ctcp

echo Habilitando ECN Capability no TCP...
netsh int tcp set global ecncapability=enabled

echo Habilitando TCP Chimney...
netsh int tcp set global chimney=enabled

echo Habilitando Receive Side Scaling (RSS)...
netsh int tcp set global rss=enabled

echo Definindo autotuninglevel do TCP como normal...
netsh int tcp set global autotuninglevel=normal

echo Habilitando DCA (Direct Cache Access)...
netsh int tcp set global dca=enabled

echo Habilitando NetDMA...
netsh int tcp set global netdma=enabled

echo Configurando congestionprovider CTCP no modo supplemental custom...
netsh int tcp set supplemental custom congestionprovider=ctcp

echo Desabilitando autotuninglevel do TCP...
netsh int tcp set global autotuninglevel=disabled

echo Habilitando notificações de exclusão para SSD (TRIM)...
Fsutil behavior set disabledeletenotify 0

echo Desabilitando Dynamic Tick...
bcdedit /set disabledynamictick yes

echo Habilitando Platform Tick...
bcdedit /set useplatformtick yes

echo Excluindo valor useplatformclock...
bcdedit /deletevalue useplatformclock

echo Desabilitando NX (Data Execution Prevention)...
bcdedit /set nx AlwaysOff

echo Configurando tscsyncpolicy para Enhanced FPS...
bcdedit /set tscsyncpolicy "Enhanced FPS"

echo Configurando tscsyncpolicy para Legacy input...
bcdedit /set tscsyncpolicy "Legacy input"